spring:
  application:
    name:
      Documents
  datasource:
    url: jdbc:postgresql://localhost:5432/TTAPCM
    username: postgres
    password: 130804
    driverClassName: org.postgresql.Driver
server:
  port: 8080

jwt:
  signerKey: "df-uig-hsd-fighd-sgfids-fghdsfguds-this-is-a-super-long-secret-key-for-hs256-with-more-than-sixty-four-characters!!!"
  valid-duration: 7200 # in second
  refreshable-duration: 72000 # in seconds
jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true