spring:
  database:
    url: jdbc:postgresql://localhost:5432/data-ecommerce?createDatabaseNotExist=false&autoReconnect=true&userSSl=false&userUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  port: 8080
